name: E2E
on: [push]
jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go build -o ./bin/go-project ./src
      - uses: cypress-io/github-action@v2
        with:
          working-directory: e2e
          browser: chrome
          headless: true
          start: go run ../bin/go-project
