name: E2E
on: [push]
jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          working-directory: e2e
          browser: chrome
          headless: true
          start: go run ../src/application.go
