name: test
on:
  workflow_call:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types:
      - opened
    branches:
      - develop
      - master
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go build -o ./bin/go-project ./src
      - uses: cypress-io/github-action@v2
        with:
          working-directory: e2e
          browser: chrome
          headless: true
          start: npm run start-server
